
public class CatchingExeptions {

	public static void main(String[] args) {
		
		try {
			int[] a = new int[2];
			
			a[0] = 1;
			
			a[3] = 5;
			
			int b = a[1] / 0;
			
			
		} catch (ArrayIndexOutOfBoundsException exception) {
			System.out.println("Достъп до несъществуващ индекс");
		}  catch (Exception exception){
			System.out.println("Друга грешка");
		}

	}

}
